version: '3.9'
services:

  monitor_billing:
    restart: unless-stopped
    image: gcloud_env
    container_name: monitor_billing
    # network_mode:  host
    command:
            - /bin/bash
            - -c
            - |
              cd /mnt_src
              python monitor_billing.py  --usd_threshold 0  --seconds 3  -v info

    environment:
     - GOOGLE_APPLICATION_CREDENTIALS="/google_config/service-account-file.json"

    volumes:
     - /home/${USER}/repos/gcloud-utils/utils:/mnt_src
     - /home/${USER}/Downloads/service-account-file.json:/google_config:ro
